# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Text
from PyQt5 import QtCore, QtGui, QtWidgets
import pyshorteners

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_copy_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copy_up.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.pushButton_copy_up.setObjectName("pushButton_copy_up")
        self.pushButton_copy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copy.setGeometry(QtCore.QRect(270, 130, 75, 23))
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.pushButton_paste = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_paste.setGeometry(QtCore.QRect(270, 90, 75, 23))
        self.pushButton_paste.setObjectName("pushButton_paste")
        self.pushButton_paste_down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_paste_down.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton_paste_down.setObjectName("pushButton_paste_down")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 80, 171, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_in = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_in.setObjectName("lineEdit_in")
        self.verticalLayout.addWidget(self.lineEdit_in)
        self.lineEdit_out = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_out.setObjectName("lineEdit_out")
        self.verticalLayout.addWidget(self.lineEdit_out)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.shortener = pyshorteners.Shortener()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.short)
        self.pushButton_copy.clicked.connect(self.copy)
        self.pushButton_paste.clicked.connect(self.paste)
        self.pushButton_paste_down.clicked.connect(self.paste_down)
        self.pushButton_copy_up.clicked.connect(self.copy_up)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "bit.ly Link Shorter"))
        self.pushButton.setText(_translate("MainWindow", "Short"))
        self.pushButton_copy.setText(_translate("MainWindow", "Copy"))
        self.pushButton_paste.setText(_translate("MainWindow", "Paste"))
        self.pushButton_copy_up.setText(_translate('MainWindow', 'Copy'))
        self.pushButton_paste_down.setText(_translate('MainWindow', 'Paste'))

    def short(self):
        try:
            _in = self.lineEdit_in.text()
            
            short = self.shortener.tinyurl.short(_in)

            self.lineEdit_out.setText(short)
        except Exception as e:
            self.lineEdit_in.setText(str(e))

    def copy(self):
        self.lineEdit_out.selectAll()
        self.lineEdit_out.copy()
    
    def paste(self):
        self.lineEdit_in.setText('')
        self.lineEdit_in.paste()

    def paste_down(self):
        self.lineEdit_out.setText('')
        self.lineEdit_out.paste()

    def copy_up(self):
        self.lineEdit_in.selectAll()
        self.lineEdit_in.copy()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
